server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.6.1
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller
mj:
  accounts[0]:
    userToken: MTI1MjQ2MDIwMDk5NzI5NDE4Mg.GWNa1L.f6M2A63H-du65qsxwxJOeXn945B7o8Hjxi2Hhg
    guild-id: 1252467529645953125
    channel-id: 1252467529645953128
    coreSize: 1
    queueSize: 10
    tag: ai,fast
  accounts[1]:
    userToken: MTI1MjQ2ODQ1NzQ5MzIzNzg0Mw.G2R0fT.o6HYw4bovrhBfQ5YKOcIfI5FlCbxGuMu0XIRpY
    guild-id: 1252468823081222154
    channel-id: 1252468823081222157
    coreSize: 1
    queueSize: 10
    tag: fast



  notify-hook: http://aigc.xcwhai.com/xbj/midjounery/callback
  task-store:
    type: redis
    timeout: 60d

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: aigc#$%^&*(0
