server:
  port: 8081
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.6.1
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller
mj:
  accounts[0]:
      userToken: MTIyMTMzMDE0NzY2ODY1NjE1MQ.Gvh7Sd.ys7Q1oXmmZgMSgaIHj5T2GtjDKLa2ptAbQPfkU
      guild-id: 1221334710953840641
      channel-id: 1221334711461478462
  discord:
    guild-id: 1221334710953840641
    user-token: MTIyMTMzMDE0NzY2ODY1NjE1MQ.Gb2a1o.z3gQw6_3KqX1sUgvpXQUj166RjSk-ZUnrp_y_Q
    channel-id: 1221334711461478462
  notify-hook: http://47.103.25.45:8080/midjounery/callback
#  task-store:
#    type: redis
#    timeout: 90d
#
#spring:
#  redis:
#    host: 47.103.25.45
#    port: 6379
#    password: aigc#$%^&*(0