server:
  port: 8081
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.6.1
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller
mj:
  accounts[0]:
      userToken: MTIyMTMzMDE0NzY2ODY1NjE1MQ.G7tgkA.BbzAGg_QBZyRn_1C8bvb0Ro1E3EnQNbJLzaec0
      guild-id: 1221334710953840641
      channel-id: 1221334711461478462
  discord:
    guild-id: 1221334710953840641
    user-token: MTIyMTMzMDE0NzY2ODY1NjE1MQ.G7tgkA.BbzAGg_QBZyRn_1C8bvb0Ro1E3EnQNbJLzaec0
    channel-id: 1221334711461478462
  notify-hook: http://aigc.xcwhai.com/xbj/midjounery/callback
#  task-store:
#    type: redis
#    timeout: 90d
#
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: aigc#$%^&*(0