server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.6.1
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources:
          - com.github.novicezk.midjourney.controller
mj:
#  accounts[0]:
#    userToken: MTIyODk2MTU2NTYzODY2MDExNg.G4bRhA.EZkEGzYm_-Ff3z7onrK8vCnjnIh8Cmt68aAwb8
#    guild-id: 1228962965617901568
#    channel-id: 1228962965617901571
  accounts[0]:
    userToken: MTIyODkxOTIxMjc1NjQzNTA1NA.G--myC.ZQM07opyzxhlezzLATgb3KhAtjOohFOw-QElI0
    guild-id: 1228952985460015155
    channel-id: 1228952986097811499
    coreSize: 10
    queueSize: 20
#  accounts[0]:
#    userToken: MTIyMDI0OTg5MjgxMTk2NDQzNw.G_4Bmd.TDpsOeLVBNPYRzJqpz5H_LpBmvECCg8nCDmKec
#    guild-id: 1220251207642255390
#    channel-id: 1220251207642255393
#  accounts[1]:
#    userToken: MTIyMTMzMDE0NzY2ODY1NjE1MQ.GhHgoB.Vm7wT1Jqbo_IP9zLkpcwmBIYXhLDxIMaXQL-Vw
#    guild-id: 1221334710953840641
#    channel-id: 1221334711461478462
#  accounts[2]:
#    userToken: MTE4MTg2NTkxNTU1ODY1ODA5MQ.GSQ0qo.RdH353bUZnrpgDfXxsS2jtdhAYtEa5wlFdxJhk
#    guild-id: 1181866555231965285
#    channel-id: 1181866555231965288
  discord:
    guild-id: 1220251207642255390
    user-token: MTIyMDI0OTg5MjgxMTk2NDQzNw.GIXRMZ.7HkjmSWzN3uqWwnRKzAgpbMGhVyvAdoXJ2wvEM
    channel-id: 1220251207642255393


  notify-hook: http://aigc.xcwhai.com/xbj/midjounery/callback
  task-store:
    type: redis
    timeout: 10000d

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: aigc#$%^&*(0